### ISSUE TITLE
For search, make it not case sensitive

### ISSUE THREAD

**Issue by brownrout** [eecs394-spr15/Gold#7]

**Comment by k5dash** [comment]
Also add rating search. like rate>3/10, date range search

**Comment by brownrout** [comment]
Will do right now

**Comment by k5dash** [comment]
Do you prefer a date picker instead of text search? I saw some Angular data picker plug in online.

**Comment by brownrout** [comment]
Yeah, that might work better at least for date. And filter bar for the rating too with a dropdown and multiple selectors (check marks)
